### ISSUE TITLE
Add Settings cells into Storyboard

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#13]
* [x] Per https://github.com/DoSomething/LetsDoThis-iOS/pull/7#commitcomment-11217391 -- Create settings table cells in Storyboard

@ryangrimm For the cells that transition to different view controllers, I assume we can just set up segues. For the Logout button, which pulls up the Action Sheet, are we able to connect an IBAction to a cell to present the Action Sheet on touch events?

* [x] Display Settings VC modally and dismiss VC upon logout, remove manual segue back per comments below

**Comment by ryangrimm** [comment]
Correct, we can setup segues for cells that transition to a different view controller. For the action sheet, they are technically deprecated in iOS 8 and UIAlertController is preferred instead. Regardless, sadly that’s not something that can be setup in a storyboard (as far as I know). However, nothing stopping us from using the usual didSelectRowAtIndexPath method to capture that and display it.

As a side note, regarding the logout, if we present the settings modally and dismiss it on logout, the login view controller will automatically be show. This happens because the viewDidAppear method is called on the LDTTabBarController which presents the login view controller when there isn’t a session. So we could skip the manual segue back to the tab bar controller.

**Comment by aaronschachter** [comment]
Ah ok, that sounds good, will add that into this issue description as well.

**Comment by aaronschachter** [comment]
Btw -- am using `UIAlertController`.  Renamed the method name from `logoutActionSheet` to  `confirmLogout` here https://github.com/aaronschachter/LetsDoThis-iOS/commit/4a3c70470711c8887ed09fd424bba93f6ba07212
