### ISSUE TITLE
Handle invalid API session tokens

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#505]
- [x] implement always-success logout, to prevent situation where user's session token is invalid and she can't log out

- [ ] once Northstar endpoint for checking validity of session token exists, check for valid session token once app starts up 

### old issue: 

If an API key is inactivated, well, the app won't run at all. But, if you're already signed in from a previous session, the app will keep loading on the Main Feed and never push out to the User Connect VC. We should at least push to User Connect VC in this scenario... I think? The API key failing is just one way to test... but if the API goes down, I suppose we don't want to push to User Connect but stay on Epic Fail

Refs https://github.com/DoSomething/LetsDoThis-iOS/blob/ea012b2721724da729611cd1cc6da3d555e9de5e/Lets%20Do%20This/Controllers/Campaign/LDTCampaignListViewController.m#L108

**Comment by aaronschachter** [comment]
In the scenario described above (https://github.com/DoSomething/LetsDoThis-iOS/issues/505#issuecomment-157772603) -- we save a session ID [per environment](https://github.com/DoSomething/LetsDoThis-iOS/blob/8ecea52de115ee2377e2b5b26c93830c66843f53/Lets%20Do%20This/Networking/DSOUserManager.m#L65). Step 2 would be checking for the session ID from production, not staging. It does sound like that the production session ID expired though.

**Comment by tongxiang** [comment]
Re: [this comment made above](https://github.com/DoSomething/LetsDoThis-iOS/issues/505#issuecomment-157789308). 

`LDTCampaignListViewController.m` calls `loadMainFeed` when first loaded, which calls `syncCurrentUserWithCompletionHandler` which both 1) calls `setHttpHeaderFieldSession` with the retrieve session token, as well as 2) calls `loadUserWithUserId`, which then hits the `retrieveAUser`   endpoint. 

Whew! That was long. But the `retrieveAUser` endpoint **doesn't need a sessionId** to return the user. So while we're sending an invalid sessionId, it's actually expected behavior for the main feed to load, and for no epic fail controller to show up when the main feed loads. 

Insofar as the error returned when we do have an invalid session id: 
```
error.code = -1011
error.localizedDescription = Request failed: unauthorized (401)
error.readableMessage = Token mismatched
error.domain = com.alamofire.error.serialization.response
```
#### Questions for @aaronschachter : 
1. Would it be a good idea for us to remove the `[[DSOAPI sharedInstance] setHTTPHeaderFieldSession:sessionToken];` call from `syncCurrentUserWithCompletionHandler`, since the sessionToken isn't actually necessary in the API calls made? 
2. Since we currently don't have an endpoint in Northstar that checks for a valid session token, it might not be easy/reasonable for us to make the valid token check when the main feed loads. In addition to implementing an always-success logout, should we check for the `-1011` error code in the places where we make API calls that require a session token? Then, we can logout if we receive that error.

**Comment by aaronschachter** [comment]
1. Removing it from that method right now would break all of the other API requests that need it, so not a great idea unless we refactor the `DSOAPI` methods to unset/set the sessionToken header field when appropriate. As we chatted about in Slack, it would make sense for us to eventually add a sessionToken to this request -- make sure the user we're accessing is someone the logged in user has access to.

2. Right, we're stuck on checking the session when the Main Feed loads. In theory it def makes sense to check for the Token mismatched error upon posting a Signup or Reportback, but this is actually a way bigger lift -- there's 3 screens to check from and then push the Login modal if expired (Campaign List, Campaign Detail, Submit Reportback). I would prefer we just wait to handle these situations until the Northstar endpoint exists -- as we could easily just do the check once when the app starts up. We wouldn't even need the extra check if the Retrieve a User endpoint required a sessionToken.

For now, the always success logout will at least unblock Marah from using the app on her device... and allows other users a way to at least use the app if the same thing happens (they'd just have to know to logout :confused:  ) We could potentially add a custom message looking for that 401 error code ("Whoops something's up please go to your profile click settings and logout") but for now let's keep things simple and not go that route.

**Comment by tongxiang** [comment]
Great, thanks.

**Comment by tongxiang** [comment]
@jonuy--thoughts on Aaron's comment above re: adding a sessionToken check to the getUser request in Northstar? 
>As we chatted about in Slack, it would make sense for us to eventually add a sessionToken to this request -- make sure the user we're accessing is someone the logged in user has access to.

**Comment by jonuy** [comment]
> add a sessionToken to this request

I think it's unlikely that we're gonna be doing that work some time soon. Doesn't this same API call need to be made to get info about other users? At least I'm pretty sure that's what Android is doing when you click on someone else's name.

**Comment by aaronschachter** [comment]
Hm yea, good point @jonuy  -- just having the endpoint to test whether or not the session is valid should it. @tongxiang i don't think we need to implement the 3rd item you listed -- checking the session is ok upon app start should be enough.

**Comment by tongxiang** [comment]
:+1: @aaronschachter

**Comment by aaronschachter** [comment]
I was able to recreate the token mismatched on my device I had tapped logout but I think I might have quit the app (or disconnected my device from xcode) before things finished, leaving my phone in an unusable state. Even if you delete the app it still happens (which I believe is because the KeyChain stuff doesnt get deleted upon uninstall)

**Comment by aaronschachter** [comment]
here's the error to look for:

> Error -1011: Request failed: unauthorized (401)
loadCampaignSignupsForUser:completionHandler:errorHandler:
users/_id/563bb421469c64d9058b4644/campaigns

**Comment by aaronschachter** [comment]
Can re-open this issue (or create a new one) if/when  https://github.com/DoSomething/northstar/issues/186 happens
