### ISSUE TITLE
Profile: Doing section

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#659]
**Updated:**

Add arrows to the Prove It section

**Original:**
*  Public user profile: brings to campaign
* If it's the Self profile, there is a Submit Reportback button. Should prompt to submit Reportback for the campaign, and update Profile with updated photo (or present Campaign Detail?)

**Comment by aaronschachter** [comment]
No longer displaying a Prove It button with the Submit Reportback button, because it's super squashed an iPhone 5:
![screen shot 2016-02-12 at 2 17 42 pm](https://cloud.githubusercontent.com/assets/1236811/13111990/f4dee876-d556-11e5-852a-f65a62e3d4aa.png)

**Comment by lkpttn** [comment]
Due to limited space on iPhone 5 and below, we need to rethink the "Prove It" button directly on the hub that shows in each cell. At smaller widths it becomes untenable.

Our current solution is to have the entire cell link back to the campaign detail page and signify this with the disclosure arrow. This means that you can no longer reportback from the hub, but you get much better tap targets and information in each hub cell.

The width of the text box in each cell should be 16pts from the left margin and 16pts from the disclosure arrow.
