### ISSUE TITLE
Pass styles into RCTRootView from LDTTheme

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/LetsDoThis-iOS#779]
DRY:
* [ ] Font family
* [ ] Font sizes
* [ ] Relevant colors (`ctaBlueColor`)

**Comment by lkpttn** [comment]
We should use this to also adjust some of the sizes and fonts for readability. We currently use Brandon Bold and Brandon Medium, but need to change Medium to Regular.

Headings are for news items, and are Brandon Grotesque Bold
- Move up from 18pts to 20pts.

Subheadings are for things like campaign CTAs
- Same size as headings (20pts) but are Brandon Regular instead of Bold

Body text is moving up from 15pt to 16pt Brandon Regular.

**Comment by aaronschachter** [comment]
@lkpttn Combining with constants found in [`LDTTheme.m`](https://github.com/DoSomething/LetsDoThis-iOS/blob/cf880745f3eabf3c79dd064eb36ad1636e3317ad/Lets%20Do%20This/Views/Base/LDTTheme.m#L11), does this look correct?

Text style | Font size | Font weight
------------ | ------------- | -------------
Caption | 13 | Normal
Body | 16 | Normal
Subheading | 20 | Normal
Heading | 20 | Bold
Title | 24 | Bold

**Comment by aaronschachter** [comment]
Font sizes have been updated and can be edited within [`LDTTheme.m`](https://github.com/DoSomething/LetsDoThis-iOS/blob/b6b3d1ace0f40ba6c8e3cf5269abe086a37cb9ad/Lets%20Do%20This/Views/Base/LDTTheme.m#L12)
